# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.6457, 0.0086, 0.8894, 0.7686, 0.8784, 0.0176, 0.3519],
        [0.0709, 0.3125, 0.9137, 0.4547, 0.1285, 0.0186, 0.6517],
        [0.8783, 0.5025, 0.1637, 0.6037, 0.1724, 0.3542, 0.1558],
        [0.9702, 0.8125, 0.9065, 0.2042, 0.8489, 0.3314, 0.4247],
        [0.2880, 0.6733, 0.0950, 0.5474, 0.4828, 0.2355, 0.2835],
        [0.4333, 0.2323, 0.1987, 0.3190, 0.4816, 0.4087, 0.1729],
        [0.3535, 0.1193, 0.9445, 0.5896, 0.4824, 0.3779, 0.4920]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
second = torch.rand(1,7)

# Perform matrix multiplication
torch.matmul(tensor, second.T)

tensor([[0.8975],
        [0.5275],
        [0.6193],
        [1.2810],
        [0.9270],
        [0.6712],
        [0.7490]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
um = torch.rand(7,7)
dois = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(um, dois.T)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tres = torch.rand(2,3).to(device)
quatro = torch.rand(2,3).to(device)
tres, quatro

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
novo_tensor = torch.matmul(tres, quatro.T)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"Maximum: {novo_tensor.max()}")

# Find min
print(f"Minimum: {novo_tensor.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Index do maior valor {novo_tensor.argmax()}")

# Find arg min
print(f"Index do menor valor {novo_tensor.argmin()}")

Index do maior valor 3
Index do menor valor 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
aleatorio = torch.rand(1, 1, 1, 10)

# Remove single dimensions
menos_dimensao = aleatorio.squeeze()

# Print out tensors and their shapes
print(f"Tensor {aleatorio, aleatorio.shape}")
print(f"Novo tensor: {menos_dimensao, menos_dimensao.shape}")

Tensor (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
Novo tensor: (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
